# Generated by Django 2.1.15 on 2020-12-23 06:11

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.exercise_image_file_path),
        ),
    ]
